In [1]:
import numpy as np
# when i am writing this code i get the below error. Why am i getting this error.
rand_mat=np.random.rand(5,5)
print(rand_mat)

[[0.73445126 0.82364979 0.77503994 0.75916622 0.36267637]
 [0.7883928  0.22855838 0.93871102 0.28910796 0.82048963]
 [0.11121096 0.40259543 0.75601581 0.773596   0.66251312]
 [0.54465372 0.64278988 0.11122945 0.3155275  0.93419421]
 [0.69108575 0.60972629 0.07119279 0.18713058 0.49172764]]


In [6]:
def addtwo(x):
    return x + 2
nums = [21,32,20]
print(list(map(lambda x: x + 2,nums)))
print(list(map(addtwo,nums)))

[23, 34, 22]
[23, 34, 22]


In [14]:
from itertools import chain

def flat_map(func, iterable):
    """Function to perform flatMap operation on an iterable using a given function."""
    return list(chain.from_iterable(map(func, iterable)))

# Example usage
words = ['Hello', 'world', 'in', 'Python Rust C#']
result = flat_map(lambda x: x.split(), words)
print(result)  # Output: ['Hello', 'world', 'in', 'Python']


['Hello', 'world', 'in', 'Python', 'Rust', 'C#']


In [16]:
def flat_map_list(lst):
    """Function to flat map a list of lists."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(item)
        else:
            result.append(item)
    return result

# Example usage
my_list = [1, 2, 3, [4, 5, 6], [33, 4], 3]
result = flat_map_list(my_list)
print(result)  # Output: [1, 2, 3, 4, 5, 6, 33, 4, 3]


[1, 2, 3, 4, 5, 6, 33, 4, 3]


In [20]:
X=(20,23,-50,5.6,98)
print(X[2:-1])

(-50, 5.6)


# Dict

In [25]:
stocks = {"msft": [1,2,3,4],"ibm": [43,453,53,]}

In [27]:
stocks.keys()

dict_keys(['msft', 'ibm'])

In [26]:
stocks.values()

dict_values([[1, 2, 3, 4], [43, 453, 53]])

In [30]:
stocks["msft"][:2]

[1, 2]

In [31]:
stocks["msft"][:-1]

[1, 2, 3]

In [33]:
stocks.pop("ibm")

[43, 453, 53]

In [34]:
stocks

{'msft': [1, 2, 3, 4]}

In [42]:
i = 10
if i > 10:
    print("x")
elif i > 5:
    print("x")

x


In [44]:
a = b = True
if (a == b):
    print("hello")
else:
    print("Well Done")

hello


In [46]:
list(range(1,10,4))

[1, 5, 9]

In [47]:
list(range(1,10,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [49]:
list(range(1,10,-4))

[]

In [50]:
list(range(-10,10,4))

[-10, -6, -2, 2, 6]

In [51]:
list(range(-10,10,-4))

[]

In [52]:
print(range(5))

range(0, 5)


In [54]:
x = [1, 2, 3, 4, 5]
while x:
    print(x.pop(0))

1
2
3
4
5


In [56]:
"1" + str(1)

'11'

In [57]:
a = 10
b = 5.1
add = a + b
type(add)

float

In [58]:
5 == (3 + 2)

True

In [59]:
a = 3
print(a + (33))

36


In [60]:
a = 3.5
int(a)

3

In [61]:
a = '5a'
int(a)

ValueError: invalid literal for int() with base 10: '5a'

In [62]:
area = 0.5 * 10 * 5 
print("Area of triangle:", area)

Area of triangle: 25.0


In [63]:
v = 10
w = 25
x = 70
y = 2
z = (v + w) * (x / y)

In [64]:
z

1225.0

In [82]:
a = 10 
b = 5
print("A and B before swapping {},{}".format(a,b))
temp = a #create a third variable and assign the value of a to it
#write the missing code(code missing here)
a = b
b = temp #value of a is in third variable so assign the value to b
print("A and B after swapping {},{}".format(a,b))

A and B before swapping 10,5
A and B after swapping 5,10


In [83]:
temp = b

In [81]:
a,b

(10, 10)

In [84]:
repeated_list = [2] * 4
print(repeated_list)

[2, 2, 2, 2]


In [85]:
alphabet = ['a','b','c']
for i in alphabet:
    print(i)

a
b
c


In [87]:
number = [1, 12, 24, 36, 11, 20,50]
for i in number:
 sq = i * i
 print(sq)

1
144
576
1296
121
400
2500


In [89]:
color = ['white','red', 'blue', 'green','blue','yellow', 'black']
color.pop(5)

'yellow'

In [90]:
color

['white', 'red', 'blue', 'green', 'blue', 'black']

In [91]:
color.remove(3)

ValueError: list.remove(x): x not in list

In [92]:
len(color)

6

In [93]:
car = { "brand" : "Audi","model" : "Q2", "year" : 1980}
print(car)

{'brand': 'Audi', 'model': 'Q2', 'year': 1980}


In [3]:
for i in range(-10, 0, 1):
    print(i)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


In [4]:
n = 8
for i in range(1, 11):
 print("{} ^ {} =".format(n, i), n**i)

8 ^ 1 = 8
8 ^ 2 = 64
8 ^ 3 = 512
8 ^ 4 = 4096
8 ^ 5 = 32768
8 ^ 6 = 262144
8 ^ 7 = 2097152
8 ^ 8 = 16777216
8 ^ 9 = 134217728
8 ^ 10 = 1073741824


In [6]:
def mths(a, b):
 print(a + b)
 print(a - b)
 print(a * b)
 print(a // b)
 
mths(9, 5)

14
4
45
1


In [7]:
def power(a, b):
    return a ** b
power(7,2)

49

In [8]:
def convert(celsius):
    fah = 1.8 * celsius + 32
    print("Temperature in Fahrenheit =", fah)
convert(20)

Temperature in Fahrenheit = 68.0


In [10]:
def my_function(a, b, *args,**kwargs):
    return a+b
my_function(5,6)

11

In [13]:
def fun(A, B=30): # A is positional and B is keyward
    return A + B

In [12]:
fun(A=10)

40