In [72]:
import numpy as np
import pandas as pd
#from google.colab import drive
#drive.mount('content/drive')

In [73]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))

In [74]:
demo_matrix[0:3, 1:3]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [81]:
demo_array = np.array(np.arange(1,11))

In [82]:
demo_array[:7]=5

In [83]:
demo_array

array([ 5,  5,  5,  5,  5,  5,  5,  8,  9, 10])

In [84]:
import numpy as np
demo_array = np.arange(0,10)
demo_array<3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [85]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])
flowers['daisy']

5

In [90]:
data_customer = pd.DataFrame({'customer': [101,102,103,104]
                           ,'category': ['cat2','cat2','cat1','cat3']
                           ,'important': ['yes','no','yes','yes']
                           ,'sales': [123,52,214,663]
                           })
data_customer

customer category important  sales
0       101     cat2       yes    123
1       102     cat2        no     52
2       103     cat1       yes    214
3       104     cat3       yes    663

In [89]:
data_customer['category'].value_counts()

cat2    2
cat1    1
cat3    1
Name: category, dtype: int64

In [91]:
data_customer.sort_values(by='sales',ascending=False)

customer category important  sales
3       104     cat3       yes    663
2       103     cat1       yes    214
0       101     cat2       yes    123
1       102     cat2        no     52

In [92]:
data_customer.loc[[1,2], ['customer', 'sales']]

customer  sales
1       102     52
2       103    214

In [95]:
data_customer.groupby(['customer'])['sales'].mean()

customer
101    123.0
102     52.0
103    214.0
104    663.0
Name: sales, dtype: float64

In [94]:
data_cust(['customer'])['sales'].mean()

NameError: name 'data_cust' is not defined

In [2]:
arr_str = ['aa','bb','cc']
arr_num = [1,2,3]

In [4]:
np_arr_str = np.array(arr_str)
np_arr_num = np.array(arr_num)

In [5]:
np_arr_str

array(['aa', 'bb', 'cc'], dtype='<U2')

In [7]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
matrix * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
type(matrix)

numpy.ndarray

In [11]:
sports = ['Cricket', 'Football', 'Tennis', 'Golf', 'Baseball']
sports_new = np.array(sports)
print(sports_new)

['Cricket' 'Football' 'Tennis' 'Golf' 'Baseball']


In [15]:
np.arange(1,14,3)

array([ 1,  4,  7, 10, 13])

In [18]:
l = np.linspace(1,10)

In [19]:
len(l)

50

In [26]:
np.linspace(start=10,stop=20,num=10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [23]:
?np.linspace

In [27]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
np.zeros(10).reshape(10,1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
vec = np.arange(10, 20, 3)
print(vec)

[10 13 16 19]


In [34]:
vec = np.linspace(10,20,3)
print(vec)

[10. 15. 20.]


In [35]:
vec = np.zeros([2,3])
print(vec)

[[0. 0. 0.]
 [0. 0. 0.]]


In [36]:
vec1 = np.arange(0, 12)
vec2 = vec1.reshape(4, 3)
print(vec2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [37]:
vec = np.arange(0,5) 
print(vec.reshape((2,3)))

ValueError: cannot reshape array of size 5 into shape (2,3)

In [38]:
vec1 = [10,15,20]
vec2 = [15,25,35]
print(vec1+vec2)

[10, 15, 20, 15, 25, 35]


In [39]:
vec1 = np.linspace(20,50,4)
vec2 = np.linspace(100,120,3)
print(vec1 + vec2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [40]:
vec = np.arange(2,5,1)
print(1/vec)
print(vec**2)

[0.5        0.33333333 0.25      ]
[ 4  9 16]


In [41]:
mat1 = np.arange(1,5).reshape(2,2)
mat2 = np.eye(2)
print(mat1/mat2)

[[ 1. inf]
 [inf  4.]]


c:\temp\ipykernel_28836\3306162440.py:3: RuntimeWarning: divide by zero encountered in divide
  print(mat1/mat2)


In [42]:
mat1 = np.arange(-9,0,1).reshape(3,3)
print(np.min(mat1))
print(np.max(mat1))

-9
-1


In [49]:
 x = np.arange(-9,0,1)

In [50]:
x

array([-9, -8, -7, -6, -5, -4, -3, -2, -1])

In [51]:
x[2:4]

array([-7, -6])

In [52]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[1][1])

5


In [53]:
vec = np.array([4,7,8,9,10,6,1])
print(vec[vec>6])

[ 7  8  9 10]


In [54]:
vec1 = np.array([4, 7, 8, 9, 10, 6, 1])
vec1[vec1>6] = 2
print(vec1)

[4 2 2 2 2 6 1]


In [56]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
matrix = np.arange(1,10).reshape(3,3)
matrix[0:2,1:2] = 0
print(matrix)

[[1 0 3]
 [4 0 6]
 [7 8 9]]


In [57]:
import numpy as np
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = array1


In [58]:
array1[0:2,1:2] = 0

In [59]:
array2

array([[1, 0, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [60]:
array1

array([[1, 0, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [61]:
import pandas as pd

In [62]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [63]:
day = ['day1', 'day2', 'day3', 'day4']
temperature = [31, 28, 30, 32] #temperature in degree Celsius
temp_data = pd.Series(temperature, index=day)

In [71]:
temp_data[2:]

day3    30
day4    32
dtype: int64

In [72]:
array1

array([[1, 0, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [79]:
array1[1:2:2]

array([[4, 0, 6]])

In [80]:
df = pd.DataFrame({'num_legs': [2, 4, 8, 0],
                    'num_wings': [2, 0, 0, 0],
                    'num_specimen_seen': [10, 2, 1, 8]},
                    index=['falcon', 'dog', 'spider', 'fish'])


In [83]:
df

num_legs  num_wings  num_specimen_seen
falcon         2          2                 10
dog            4          0                  2
spider         8          0                  1
fish           0          0                  8

In [88]:
df[1::2]

num_legs  num_wings  num_specimen_seen
dog          4          0                  2
fish         0          0                  8

In [90]:
df[::2]

num_legs  num_wings  num_specimen_seen
falcon         2          2                 10
spider         8          0                  1

In [102]:
df

num_legs  num_wings  num_specimen_seen
falcon         2          2                 10
dog            4          0                  2
spider         8          0                  1
fish           0          0                  8

In [118]:
df.loc[0]

KeyError: 0

In [106]:
df.loc["dog":"fish",["num_wings"]]

num_wings
dog             0
spider          0
fish            0

In [109]:
df.iloc[1:,1]

dog       0
spider    0
fish      0
Name: num_wings, dtype: int64

In [110]:
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data

day  calories  duration_min
0  day1       450            30
1  day2       300            25
2  day3       345            29
3  day4       520            39
4  day5       600            48

In [111]:
calorie_data.loc[[1,2],['calories']]

calories
1       300
2       345

In [112]:
calorie_data.iloc[[1,2],[1]]

calories
1       300
2       345

In [116]:
calorie_data.loc[1]

day             day2
calories         300
duration_min      25
Name: 1, dtype: object

In [115]:
calorie_data.iloc[0]

day             day1
calories         450
duration_min      30
Name: 0, dtype: object

In [117]:
calorie_data.index

RangeIndex(start=0, stop=5, step=1)

In [121]:
calorie_data[calorie_data["calories"] > 400]

day  calories  duration_min
0  day1       450            30
3  day4       520            39
4  day5       600            48

In [122]:
calorie_data.loc[calorie_data["calories"] > 400]

day  calories  duration_min
0  day1       450            30
3  day4       520            39
4  day5       600            48

In [123]:
calorie_data.iloc[calorie_data["calories"] > 400]

NotImplementedError: iLocation based boolean indexing on an integer type is not available

In [124]:
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data

day  calories  duration_min
0  day1       450            30
1  day2       300            25
2  day3       345            29
3  day4       520            39
4  day5       600            48

In [125]:
calorie_data.loc[calorie_data['calories']>500]

day  calories  duration_min
3  day4       520            39
4  day5       600            48

In [126]:
calorie_data.drop('duration_min', axis=1)

day  calories
0  day1       450
1  day2       300
2  day3       345
3  day4       520
4  day5       600

In [1]:
import datetime
date = datetime.date(2022, 1, 29)
print(date)

2022-01-29


In [2]:
date.dt.month

AttributeError: 'datetime.date' object has no attribute 'dt'

In [4]:
array_1 = np.linspace(0,20,6)

In [5]:
array_2 = np.arange(0,20,6)

In [8]:
len(array_1) - len(array_2)

2

In [9]:
array_2

array([ 0,  6, 12, 18])

In [10]:
mat = np.matrix([[ 1, 4, 9, 121, 144, 169],
                [ 16, 25, 36, 196, 225, 256], 
                [ 49, 64, 81, 289, 324, 361]])

In [11]:
np.mean(mat)

131.66666666666666

In [12]:
a = np.arange(0,20)
print(a[2:7])

[2 3 4 5 6]


In [13]:
a[a<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.cos([0, 1, 2, 3, 4]) 

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [15]:
list_1 = [1,2,3] 
list_2 = [4,5,6]
new_list = list_1 + list_2

In [16]:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
new_array = array_1 + array_2

In [18]:
len(new_list) == len(new_array)

False

In [19]:
new_list

[1, 2, 3, 4, 5, 6]

In [20]:
new_array

array([5, 7, 9])

In [21]:
mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])

In [22]:
mat

array([[1, 2, 1],
       [4, 5, 9],
       [1, 8, 9]])

In [23]:
mat[1]=5

In [24]:
mat

array([[1, 2, 1],
       [5, 5, 5],
       [1, 8, 9]])

In [25]:
array_1 = np.array([1, 2, 3, 5, 8])
array_2 = np.array([0, 3, 4, 2, 1])
new_array = array_1+ array_2
final_array = new_array*array_1
print(final_array[2])

21


In [26]:
final_array

array([ 1, 10, 21, 35, 72])

In [28]:
np.ones([2, 2]).shape

(2, 2)

In [29]:
n1 = np.matrix([[121, 144, 169], [196, 225, 256], [ 289, 324, 361]])

In [30]:
n2 = np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])

In [31]:
n1 @ n2

matrix([[1786, 1880, 3017],
        [2725, 2933, 4712],
        [3862, 4220, 6785]])

In [32]:
!dir

 Volume in drive C is Windows
 Volume Serial Number is 66D7-08B7

 Directory of C:\sources\BAU\python\IntroPython

06/16/2023  08:43 PM    <DIR>          .
06/16/2023  08:43 PM    <DIR>          ..
06/16/2023  08:29 PM    <DIR>          .ipynb_checkpoints
06/10/2023  06:11 PM            22,192 Data Structure.ipynb
06/03/2023  04:23 PM            23,247 Hands_on_notebook_Data_Structures_1.ipynb
06/03/2023  08:11 PM            26,923 Hands_on_notebook_Data_Structures_2-1.ipynb
06/16/2023  08:29 PM            60,197 Hands_on_Notebook_NumPy_v1.ipynb
06/16/2023  07:59 PM           350,043 Hands_on_Notebook_Pandas-1.ipynb
06/16/2023  08:43 PM            64,324 Numpy.ipynb
06/10/2023  06:02 PM            12,471 OOP_in_python.ipynb
06/15/2023  03:25 PM    <DIR>          Untitled Folder
               7 File(s)        559,397 bytes
               4 Dir(s)  26,751,733,760 bytes free


In [36]:
df = pd.read_csv('books.csv')

In [37]:
df.head()

title  \
0                        The Hunchback of Notre-Dame   
1  La Cucina Di Lidia: Recipes and Memories from ...   
2                                  Breach of Promise   
3                  Brief Interviews with Hideous Men   
4  The Killing Dance (Anita Blake  Vampire Hunter...   

                        author  average_rating         isbn13 language_code  \
0                  Victor Hugo            4.00  9780345472427         en-US   
1  Lidia Matticchio Bastianich            4.14  9780767914222         en-GB   
2             James Scott Bell            4.00  9780310243878           eng   
3         David Foster Wallace            3.86  9780349111889           eng   
4          Laurell K. Hamilton            4.13  9780425209066         en-US   

   num_pages  ratings_count  text_reviews_count          publisher  year  
0      534.0            140                  22     Modern Library  2004  
1      288.0             48                   3    Clarkson Potter  2003  
2      345.0            368                  36          Zondervan  2004  
3      273.0          18335                1155             Abacus  2000  
4      368.0          59524                 946  Berkley Hardcover  2006

In [38]:
df.shape

(5000, 10)

In [39]:
df.describe()

average_rating        isbn13    num_pages  ratings_count  \
count     5000.000000  5.000000e+03  4967.000000   5.000000e+03   
mean         3.931932  9.752758e+12   341.094021   2.017549e+04   
std          0.348741  5.129254e+11   230.986115   1.175026e+05   
min          0.000000  8.987060e+09     1.000000   0.000000e+00   
25%          3.770000  9.780345e+12   200.000000   1.050000e+02   
50%          3.960000  9.780571e+12   304.000000   7.915000e+02   
75%          4.140000  9.780871e+12   416.500000   5.348750e+03   
max          5.000000  9.789879e+12  3342.000000   2.457092e+06   

       text_reviews_count         year  
count         5000.000000  5000.000000  
mean           592.688600  2000.131800  
std           2539.539004     8.069043  
min              0.000000  1913.000000  
25%              9.000000  1998.000000  
50%             49.000000  2003.000000  
75%            249.000000  2005.000000  
max          55843.000000  2019.000000

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   title               5000 non-null   object 
 1   author              5000 non-null   object 
 2   average_rating      5000 non-null   float64
 3   isbn13              5000 non-null   int64  
 4   language_code       4923 non-null   object 
 5   num_pages           4967 non-null   float64
 6   ratings_count       5000 non-null   int64  
 7   text_reviews_count  5000 non-null   int64  
 8   publisher           5000 non-null   object 
 9   year                5000 non-null   int64  
dtypes: float64(2), int64(4), object(4)
memory usage: 390.8+ KB


In [42]:
df[df['average_rating']>4].count()

title                 2115
author                2115
average_rating        2115
isbn13                2115
language_code         2072
num_pages             2103
ratings_count         2115
text_reviews_count    2115
publisher             2115
year                  2115
dtype: int64

In [50]:
df[(df['average_rating']>4.5) & (df['ratings_count'] < 10)]

title  \
63                                             鋼之鍊金術師 9   
178                                            鋼之鍊金術師 6   
224                             Stargirl LitPlans on CD   
454   Literature Circle Guide: Bridge to Terabithia:...   
584                       Falling Angels (Luc Actar #1)   
681        Fanning the Flame: Bible  Cross  and Mission   
696                  Tyrannosaurus Wrecks (Stanley  #1)   
741   The John Deere Two-Cylinder Tractor Encycloped...   
757   The American Campaign: U.S. Presidential Campa...   
1837  The Goon Show  Volume 4: My Knees Have Fallen ...   
1856                                          鋼之鍊金術師 10   
1960  Wissenschaft der Logik: Die Lehre Vom Begriff ...   
2244  Getting a Grip on the Basics: Building a Firm ...   
2496                               Come Away My Beloved   
3178  Organizational Architecture: Designs for Chang...   
3438         Bill Gates: Computer Legend (Famous Lives)   
3706  A Wife After God's Own Heart Growth and Study ...   
3833  His Princess Devotional: A Royal Encounter Wit...   
3909                 Little Big Book for God's Children   
3927  Colossians and Philemon: A Critical and Exeget...   
4108                  Willem de Kooning: Late Paintings   
4415                                           Corvette   
4455  The Complete Theory Fun Factory: Music Theory ...   
4917                          Taxation of Mineral Rents   
4933  Oliver Wendell Holmes in Paris: Medicine  Theo...   

                             author  average_rating         isbn13  \
63                   Hiromu Arakawa            4.57  9789861156521   
178                  Hiromu Arakawa            4.58  9789861146140   
224                 Mary B. Collins            4.86  9781583372920   
454                  Tara MacCarthy            5.00  9780439271714   
584               Melissa M. Garcia            4.67  9780595377107   
681                  Chris    Green            5.00  9780310249870   
696                  Laura Driscoll            5.00  9780786845033   
741                   Don Macmillan            4.75  9780760329634   
757               James E. Campbell            5.00  9780890969403   
1837                     NOT A BOOK            5.00  9780563388692   
1856                 Hiromu Arakawa            4.60  9789861156538   
1960  Georg Wilhelm Friedrich Hegel            4.78  9783787307678   
2244                  Beth A. Jones            4.67  9781577948261   
2496             Frances J. Roberts            4.58  9781593109158   
3178                David A. Nadler            4.62  9781555424435   
3438               Sara Barton-Wood            5.00  9780739844328   
3706               Elizabeth George            4.69  9780736911689   
3833            Sheri Rose Shepherd            5.00  9781590529621   
3909                     Alice Wong            4.88  9780941807555   
3927                 R. McL. Wilson            5.00  9780567044716   
4108                Julie Sylvester            5.00  9783829602266   
4415                   Jerry Burton            4.83  9780883631218   
4455              Ian        Martin            5.00  9780851621814   
4917                   Ross Garnaut            5.00  9780198284543   
4933             William C. Dowling            5.00  9781584655800   

     language_code  num_pages  ratings_count  text_reviews_count  \
63             NaN      184.0              4                   0   
178            NaN      191.0              5                   0   
224            eng      210.0              5                   0   
454            eng       32.0              4                   1   
584            eng      216.0              1                   0   
681            eng      336.0              1                   1   
696            eng       24.0              2                   1   
741            eng      256.0              4                   0   
757            eng      314.0              0                   0   
1837          

In [57]:
df[df['language_code'] == 'eng']['average_rating'].mean()

3.931142857142857

In [58]:
df.iloc[0:5,0:4]

title  \
0                        The Hunchback of Notre-Dame   
1  La Cucina Di Lidia: Recipes and Memories from ...   
2                                  Breach of Promise   
3                  Brief Interviews with Hideous Men   
4  The Killing Dance (Anita Blake  Vampire Hunter...   

                        author  average_rating         isbn13  
0                  Victor Hugo            4.00  9780345472427  
1  Lidia Matticchio Bastianich            4.14  9780767914222  
2             James Scott Bell            4.00  9780310243878  
3         David Foster Wallace            3.86  9780349111889  
4          Laurell K. Hamilton            4.13  9780425209066

In [59]:
df.loc[[1,4],['language_code', 'num_pages', 'ratings_count']]

language_code  num_pages  ratings_count
1         en-GB      288.0             48
4         en-US      368.0          59524

In [60]:
df['num_pages'].median()

304.0

In [61]:
df['num_pages'].max()

3342.0

In [62]:
df['num_pages'].mode()

0    288.0
Name: num_pages, dtype: float64

In [63]:
df['num_pages'].mean()

341.0940205355345

In [64]:
df[df['year'] == 2010].count()

title                 15
author                15
average_rating        15
isbn13                15
language_code         15
num_pages             15
ratings_count         15
text_reviews_count    15
publisher             15
year                  15
dtype: int64

In [67]:
df[(df['publisher'] == 'DAW') & (df['average_rating'] > 4)]

title           author  \
71                           By the Sword (Valdemar)  Mercedes Lackey   
871         Storm Rising (Valdemar: Mage Storms  #2)  Mercedes Lackey   
1523       Phoenix and Ashes (Elemental Masters  #3)  Mercedes Lackey   
1583  To Battle the Gods (Jalav  Amazon Warrior  #5)     Sharon Green   
3726        Oathblood (Valdemar: Vows and Honor  #3)  Mercedes Lackey   
4367                     Joust (Dragon Jousters  #1)  Mercedes Lackey   

      average_rating         isbn13 language_code  num_pages  ratings_count  \
71              4.25  9780886774639           eng      492.0          18531   
871             4.02  9780886777128         en-US      412.0          10781   
1523            4.01  9780756402723           eng      480.0           6980   
1583            4.07  9780886771287           eng      446.0             87   
3726            4.06  9780886777739         en-GB      394.0           9786   
4367            4.02  9780756401535           eng      448.0          10113   

      text_reviews_count publisher  year  
71                   249       DAW  1991  
871                   86       DAW  1996  
1523                 229       DAW  2005  
1583                   1       DAW  1986  
3726                 103       DAW  1998  
4367                 263       DAW  2004

In [69]:
df[(df['year'] > 2010) & (df['num_pages'] > 500)].count()

title                 5
author                5
average_rating        5
isbn13                5
language_code         5
num_pages             5
ratings_count         5
text_reviews_count    5
publisher             5
year                  5
dtype: int64

In [70]:
df[df['author'] == 'Agatha Christie'].count()

title                 21
author                21
average_rating        21
isbn13                21
language_code         21
num_pages             19
ratings_count         21
text_reviews_count    21
publisher             21
year                  21
dtype: int64

In [71]:
df[(df['year'] > 2000) & (df['language_code'] == 'spa')].count()

title                 84
author                84
average_rating        84
isbn13                84
language_code         84
num_pages             83
ratings_count         84
text_reviews_count    84
publisher             84
year                  84
dtype: int64